version: "3"
services:
  postgres:
    image: library/postgres:13
    container_name: postgres
    restart: on-failure
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./postgres/:/docker-entrypoint-initdb.d/
    ports:
      - "5432:5432"

# TODO добавить сервисы
  privileges:
    build:
      context: src/privileges
    ports:
      - "8050:8080"
    depends_on:
      - postgres
    links: 
      - postgres

  flights:
    build:
      context: src/flights
    ports:
      - "8060:8080"
    depends_on:
      - postgres
    links: 
      - postgres

  gateway:
    build:
      context: src/gateway
    ports:
      - "8080:8080"
    depends_on:
      - flights

volumes:
  db-data: